### ISSUE TITLE
Connection to LinguaLibre.org via Commons ?

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#11]
Hello Kanasimi,

I tried to create a minimal bot to contribute to Wikimedia's [LinguaLibre.org](https://linguaLibre.org). Login fails. I suspect it's because it has delegated login to Commons via Oauth. I am confuse on how to connect for log in, how to connect for edit.

My objective is to create 1000 pages based on @unicode-org/unilex's 1000's files.

### Current code
```const Wikiapi = require('wikiapi');

// edit page: method 2
(async () => {
	await wiki.login('Dragons Bot', 'pass', 'https://commons.wikimedia.org/api.php');
	const wiki = new Wikiapi('https://www.lingualibre.org/api.php');
	await wiki.edit_page('User:Dragons_Bot', function(page_data) {
		return page_data.wikitext
			+ `\nHi, I'm Dragons Bot ! I plan to upload lists and others maintenances.`;
	}, {bot: 1, nocreate: 1, minor: 1});
	console.log('Done.');
})();
```

**Comment by hugolpz** [comment]
Solution:
- Works: [Special:BotPasswords](https://lingualibre.org/wiki/Special:BotPasswords) allows the creation of local bot password.
- Not explored : [:mw:OAuth/For_Developers#Node.js](https://www.mediawiki.org/wiki/OAuth/For_Developers#Node.js)
See discussion on [LinguaLibre:Bot](https://lingualibre.org/index.php?title=LinguaLibre:Bot&oldid=464934#Connexion_via_Oauth_and_Bots_for_Unilex_lists_editing)

**Comment by kanasimi** [comment]
Yes, you may try https://lingualibre.org/wiki/Special:BotPasswords
