### ISSUE TITLE
[[*/Stop]]

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#16]
In console I see :
```bash
wiki_API_page: Not exists: [[User talk:Dragons Bot@Dragons Bot/Stop]]
```
We should expect :
```bash
wiki_API_page: Not exists: [[User talk:Dragons Bot/Stop]]
```
no ?

**Comment by kanasimi** [comment]
The code is at https://github.com/kanasimi/CeJS/blob/master/application/net/wiki/page.js#L584
Usually it should be `[[User talk:Dragons Bot/Stop]]`
May you show the code calling .page()?

**Comment by hugolpz** [comment]
I got `ReferenceError: wiki_session is not defined`. Where do you put that ?

But yes, `USER='Dragons Bot@Dragons_Bot'` for sure. It's the value I use, as provided by Special:PasswordBots.


```(async () => {
    // Connect
    const targetWiki = new Wikiapi;
    await targetWiki.login(USER, PASS, API);

    // Print list to page
    await targetWiki.edit_page('User:Yug', function(page_data) {
        // console.log('pagedata',page_data)
        console.log(wiki_session)
        return page_data;
    }, {bot: 1, minor: 1, summary: 'test edit'});
    
})();
```

**Comment by FabulousCupcake** [comment]
This should be documented somewhere; I was confused why the library is screaming about `/Stop` paging not existing, only to find out after ~30 minutes that it seems to be a hardcoded/arbitrary way to stop the bot.

**Comment by hugolpz** [comment]
It's a Wikimedia best practice : a conventional button, which provides via the right url a very quick access to the admin page to block that bot.

There is a push to produce a clear documentation (#30). Still needs about a week for the core 90%. Then few months to add sugars. 👍🏼

**Comment by FabulousCupcake** [comment]
I did read over https://www.mediawiki.org/wiki/Manual:Bots and found no mentions about the Stop page, hence the confusion, but glad to hear there's plans to improve docs 👍

**Comment by hugolpz** [comment]
You are able to make it run right ? Your bot is on github ?

**Comment by FabulousCupcake** [comment]
Yes; It did not block anything, just produced mildly annoying "Stop page not found" on/after every edit.  
Creating the page and writing something in it silenced the output.
