### ISSUE TITLE
Upload file only if file does not exist ?

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#26]
Hello,
Is there a parameter for that, or should I first read the target page to check if it exists ?

I have a code working via 
```javascript
let pageData = await targetWiki.page(`File:${zi}-red.png`, {});
let isEmpty = pageData.wikitext==='';
```

It's more a documentation issue.

**Comment by kanasimi** [comment]
By default, the function will not overwrite files existed. It will throw if file exists.

**Comment by hugolpz** [comment]
(Add a `{ "force": true }` options ?)

**Comment by kanasimi** [comment]
Add a { "ignorewarnings": true } to options

**Comment by hugolpz** [comment]
I could go to `/_test_suite/test.js` to find those hidden parameters rights ?

**Comment by kanasimi** [comment]
Well.. in fact, it is in https://commons.wikimedia.org/w/api.php?action=help&modules=upload
Of course we can document it.

**Comment by hugolpz** [comment]
I like to write documentations and I still plan to do so with yours. But I still have to understand your code's rules betters. Today I understood that you base your parameters naming convention upon MediaWiki API. Good :D It still have to understand more stuff before attacking your README.md.

**Comment by kanasimi** [comment]
Yes, I wish more people to join the program development :smiley:
