### ISSUE TITLE
JSDoc3's docdash template customization

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#31]
For later. There are clearly some avenues to make more minimalist and savy doc. 👍🏼  That's pretty cool !

### See also
* https://github.com/clenemt/docdash/issues/19
* @hugolpz, [Clean API documentation writing for Javascript](https://hugolpz.medium.com/clean-api-documentation-writing-for-javascript-others-3d8902f88b15) blogpost. [Edit:] Added thanks section !

**Comment by kanasimi** [comment]
Maybe we can just left a link to examples, just like the header part of https://github.com/kanasimi/wikiapi#usage now

**Comment by hugolpz** [comment]
Opt out from side bar alphabetical method sorting ? You could organize methode order in a more semantic way. See https://github.com/clenemt/docdash/issues/6

**Comment by hugolpz** [comment]
@kanasimi , i think we can close this issue for now. We did a lot already on the doc. Optimizing the Doc UI / css to reduce chartjunk is not imperiously needed. We can return to this far later.

Also, maybe you can grand me some additional right on the project so i may create milesstones, closes issues, etc.
