### ISSUE TITLE
Create demo starter bot with basic actions

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#35]
I started a demo bot repository which will contain convenient basic codes, better organized and ready to fire.
See : [hugolpz/WikiapiJS-Eggs](https://github.com/hugolpz/WikiapiJS-Eggs)

**Comment by hugolpz** [comment]
[Work in progress] - README.md rewrite below.

----

### Install
Dependencies: `git`, `nodejs`, `npm`.

Setup:
```bash
mkdir SuperBot                 # example bot name
cd ./SuperBot                    # move in folder
npm install wikiapi           # install core library
```

### API documentation
**Open and explore [API documentation](https://kanasimi.github.io/wikiapi/).**

### Init
1) On your wiki, login or create an account, then gather your username and password in a `login.js` file:
```javascript
// login.js : I store your password and should never be git commited ! Add `login.js` to your .gitignore file.
module.exports = {
	// Human login, get an account via [[Special:CreateAccount]].
	commonsH: {
		user: 'Username Bot',
		pass: 'password',
		api : 'https://commons.wikimedia.org/w/api.php'
	},
	// Bot logins, get it via [[Special:BotPasswords]].
	commons: {
		user: 'Username Bot@Username_Bot',     // likely something like that
		pass: 'long-password',
		api : 'https://commons.wikimedia.org/w/api.php'
	},
};
```
2) Create your script using this boilerplate : 
```javascript
// commons-login.js : I just loging into the target wiki.
const Wikiapi= require('wikiapi');
const logins = require('./logins.js');

// Login credentials from .login*.js
var USER = logins.commons.user,
	PASS = logins.commons.pass,
	API  = logins.commons.api;

(async () => {
    const targetWiki = new Wikiapi;
    await targetWiki.login(USER, PASS, API);
    console.log(`Username ${USER} is connected !`);

   // CORE ACTION(S) HERE, see the API below.

})();
```

3) Edit the `CORE ACTION(S)` part to do something. Ex: 
```javascript
/* EDIT MANY ************************************************ */
// Provided list
	let list = ['Wikipedia:Sandbox', 'Wikipedia:Sandbox2', 'Wikipedia:Sandbox/wikiapi' ];
// List pages in [[Category:Chemical_elements]]
	let listMembers = await wiki.categorymembers('Chemical elements');  // array of titles
// List intra-wiki links in [[ABC]]
	let listLinks = await wiki.redirects_here('ABC');  // array of titles
// List of transcluded pages {{w:en:Periodic table}}
	let listTranscluded = await wiki.embeddedin('Template:Periodic table');

// Edit-many on members of target [[Category:Chemical_elements]]
// Add template, replace-remove vandalism, add category
	await wiki.for_each_page(
		listMembers, 
		page_data => { return `{{stub}}\n`+page_data.wikitext.replace(/Covfefe/g,'')+`\n[[Category:Bot test: edit]]`; },
		 {bot: 1, nocreate: 1, minor: 1, summary: 'Bot test: edit'}
	);
```

4) On Wikimedia's Wikis, go to [Commons:Bots/Requests](https://commons.wikimedia.org/wiki/Commons:Bots/Requests) or your [Wikipedia:Bots/Requests](https://en.wikipedia.org/wiki/Commons:Bots/Requests), follow instruction to get your bot approved. Ask for the temporary user-rights so you may demo your skillful usage of these user-rights.

**Comment by hugolpz** [comment]
@kanasimi, you don't have such demo bot on github, right ?

**Comment by kanasimi** [comment]
Yes, I have no suce a instruction. I maintain some bot codes in https://github.com/kanasimi/wikibot , although they may be too complex.

**Comment by hugolpz** [comment]
I see. Wikibot is a working prototype for a specific use but not a kick starter. Same for my Dragons Bot project.

So i have the greenlight to create a kick starter / boiler plate bot. Nice.

**Comment by hugolpz** [comment]
[Seeded](https://github.com/hugolpz/WikiapiJS-Eggs). Developments to continue there.
