### ISSUE TITLE
Edit repository details to add `wikiapijs` tag.

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#39]
- [x] WikiapiJS-eggs : tag added.
- [ ] Wikiapi

Wikiapi is too broad and non-distinctive and confusing.
WikiapiJS should be used to qualify your project, as often as possible.

![Screenshot_2021-04-06_10-37-43](https://user-images.githubusercontent.com/1420189/113683143-27c65d80-96c4-11eb-8cd4-f0e6a1cde895.png)

### Also...
May I suggest you to rename the project's title as well ? You as lightly use as of now. But with a clean documentation, elegant API code, and a very popular language (JS)... The project is going to become mediumly popular. Better to rename now.

**Comment by kanasimi** [comment]
Maybe you can provide a good name?

**Comment by hugolpz** [comment]
WikiapiJS 💯

**Comment by kanasimi** [comment]
It seems hard to rename the npm.
Maybe what we can do is to rename the example code, from `Wikiapi` to `WikiapiJS`.

**Comment by hugolpz** [comment]
- WikiapiJS - for humans.
- wikiapijs - for computers.
  - wikiapi - for npm, which is already a js ecosystem.

**Comment by kanasimi** [comment]
I have added the tag `wikiapijs`.
I am not sure that if I rename the base on github, it will raise special impacts or unexpected side effects...

**Comment by hugolpz** [comment]
Tag done = issue close.

Opening #40 : Clarify naming convention.
