### ISSUE TITLE
Upload upon : no edit of the page ?

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#42]
This is possibly not a bug.

I just [uploaded upon](https://commons.wikimedia.org/w/index.php?title=File:%E4%B8%80-red.png&diff=prev&oldid=554241075), and it does no pagecontent's changes.

```javascript
// upload
let result = await targetWiki.upload({ 
  comment: `Upload Chinese radical ${zi} in red style, raster format.`,
  text: `{{SOlicense|${zi}|${locale}|${major}.${extension}||${rad[0].replace(/^0+/,'')}|date=${today}|author=[[User:Yug|]]|license=PD-font|fontname=Arphic PL UKai}}`
  +`\n{{MakeMeAHanzi}}\n{{AnimeCJK}}`
  +`\n{{Rcat|{{Radnum|${rad[0]}}}|${rad[0]}|0||x}}`,
  filepath : `../DragonsBot/SOP/${zi}-${locale}${major}.${extension}`,
  ignorewarnings: 1, // overwrite or create,
  author: '[[User:Yug]]',
  categories:[`ShufaBot test: upload`]
});
```

Parameter `comment` is not effective.
Parameter `text` is not effective.
Parameter `author` is not effective.
Parameter `categories` is not effective.

So I plan an edit round thereafter.

**Comment by kanasimi** [comment]
You may try change text to additional_text.

**Comment by hugolpz** [comment]
It will append, right ?

**Comment by kanasimi** [comment]
Sorry, I misunderstood your meaning. Yes, this is not a bug. When you are update a file, only the file content will changed. The <code>comment</code> will only shown in the file page. The <code>text</code>, ... till <code>categories</code> will <em>all ignored</em>.
I guess what you want is like https://commons.wikimedia.org/wiki/Special:Contributions/cewbot .
I update the documents, please tell me if there are still something not clear.
