### ISSUE TITLE
`.download()` scalability ?

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#51]
Hi there,
I'm using WikiapiJS to code a _wikiapi-egg_ (script) which will download all Commons files from target categories. My 3 largest target categories currently have about 50k audios files each, files being of 1.5KB each. Do you know:
- Q1: Does WikiapiJS has such scale up in mind ?
- Q2: What are the API limitations for such mass download ?
  - Listing items: Mediawiki API has a [Categorymembers](https://www.mediawiki.org/wiki/API:Categorymembers) limit. `cmlimit=500` for regular users, `cmlimit=5000` if `apihighlimits` userright.
  - Downloads: I don't see limits on download themselves. 
- Q3: Do you handle categories with more than 500 files successfully ? (API limit)
- Q4: Do you skip already downloaded files efficiently ? (quickly)
- Q5: What should i avoid to not be blocked ?
- Q6: Do you compare local and remote files creation dates so to re-download from Commons when a new version is available ?

It's to provides the public direct and convenient dumps of LinguaLibre's audio assets on a per language basis. We want to create periodic (weekly?) dumps on our Lili server.

WikiapiJS download worked on tiny categories (files =12). See #48 code.
I'm currently reluctant to test further by fear of being banned.

----
### `.download()` bentchmark (1)
Ok, I decided to test anyway on [a category](https://commons.wikimedia.org/wiki/Category:Lingua_Libre_pronunciation_by_Yug) with n=369.
- Initial attempt : 
  - categorymembers=369
  - downloads=369 
  - runing time: 16min or 960sec --> 2.7s./file
- Removed 14 files from local directory 
- Update attempt: 
  - categorymembers=369
  - downloads=14
  - runing time: 9min or 540sec --> 38.6s./file

### Q4-related (✅ #52)
When a file already exists locally, it could be skipped faster.
Given `a` the _time per download_, `x` the _number of files to download_, `b` the _initial categorymember query time_ with estimated `b=60sec`. We could get the second attempt (update) duration to be such as `2.7*14+60 = 97.8secs` instead of 540 sec.

### Q6-related (✅ #52)
@Poslovitch pointed out that filenames are not enough, some versioning check may be ongoing so recently updated files on commons are indeed re-downloaded. ([Discord server invitation](https://discord.gg/c7M2ufzQ))
Ciencia-Al-Poder pointed out _"First of all, you should avoid redownload files that you downloaded on a previous run. The api will return you the file modification/creation time. Use it to check if the file has been updated."_ ([Discord link](https://discord.com/channels/178359708581625856/417008204669779969/925083188890595349))

**Comment by kanasimi** [comment]
1. I did not imagine this, but I reserved the possibility for this.
2. You know I have the apihighlimits permission in wiki commons, so I often use this... but it should work for users without apihighlimits permission too. There should no limit for downloading large categories.
3. I have processed for categories with 100K+ files.
4. Yes, the library will skip files existed.
5. I have never heard of wiki commons blocking people downloading files, so...
6. No. I have not coding this yet.

**Comment by hugolpz** [comment]
Q4 file skipping: Given the duration times observed above at second attempt ,(when re-downloading), the "file exists locally so skip this download" algorithm is not very efficient.

We what to keep a local dump synchronized based on Wikimedia Commons. We are talking about 700,000 files so far. According to tests duration above, the initial synchronization would take 21 days, that is ok.
But the later "updates" a week later would require about 15 days while only 1~2% of new files will require (7,000-15,000) will require download. Too long.

Do you have possible optimization at sight ?

**Comment by kanasimi** [comment]
What categories do you want to synchronize?

**Comment by hugolpz** [comment]
Aim is to provide a dump of these 128 categories.
The largest ones are 60k (ben) and 250k (fra) files.
But the point is scalability, ability to handle large categories, initial download and later periodic update. Ideally weekly.
https://commons.wikimedia.org/wiki/Category:Lingua_Libre_pronunciation

**Comment by kanasimi** [comment]
Well, it seems I need to do some works...

**Comment by hugolpz** [comment]
I don't know how cejs currently handles your queries, but I suspect you list the target files, then run an API query for each file.
API queries are limited. Download file is not.
I know of [Special:ApiSandbox queries](https://commons.wikimedia.org/wiki/Special:ApiSandbox#action=query&format=json&prop=imageinfo&generator=categorymembers&iiprop=url%7Cextmetadata%7Ctimestamp&iimetadataversion=1&iiextmetadatafilter=Categories&gcmtitle=Category%3ALingua_Libre_pronunciation-fra&gcmprop=ids%7Ctitle&gcmnamespace=6&gcmlimit=500) which using a single API call can fetch by category name few hundred files category member files, with exact file url and timestamp.

**Comment by kanasimi** [comment]
Hi. Maybe you will be interesting in `const file_data_list = await wiki.download('Category:name', { directory: './' });`

**Comment by hugolpz** [comment]
Hello Kanasimi,
Thank for this new feature which simplifies codes indeed in term of depth and replication of the source structure.

The `.download() bentchmark` section above shows `.download()` to have slow performance.
Per analysis above, I understand `.download()` to take as input objects such as:

```javascript
{ 
  "pageid":104331639,
  "ns":6,
  "title":"File:LL-Q150 (fra)-Kitel WP-%.wav"
}
```

**Such input means `.download()` must run one API call per file, which is rate limited**, resulting is important speed limitation.

I think `await targetwiki.categorymembers('Category:Lingua Libre pronunciation-cmn', { namespace: 'File' });`, when operating with `namespace: 'File'` (`ns:6`), should run smarter API queries requiring `imageinfo` (see section "Wikimedia API and group queries" above), and return objects such as : 

```javascript
{ 
  "pageid":104331639,
  "ns":6,
  "title":"File:LL-Q150 (fra)-Kitel WP-%.wav",
  "timestamp": "2021-04-25T15:49:00Z",
  "url": "https://upload.wikimedia.org/wikipedia/commons/a/a3/LL-Q150_%28fra%29-Kitel_WP-%25.wav"
},
```

If such input is provided, `.download()` can then use the `url` value to run without rate-limited API call, 20 times faster, directly on `https://upload.wikimedia.org`. The `timestamp` value allows to compare remote and local files creation times.

**Comment by kanasimi** [comment]
Well, in fact the conceptions are implemented now. The codes will do as less calls as possible. You may try it yourself.

**Comment by hugolpz** [comment]
I tested today :
- Files: 805 downloads
- Duration: 12'10" (730secs)
- Average : 1 file / 0.9 sec.

**This is 3 times better than before.** 🎇 

(I believe the script could go ~10 times faster if `categorymembers()` pass `url` and `timestamp` to `.download()` so it only/mostly hits on `https://upload.wikimedia.org` and `https://commons.wikimedia.org/w/api.php` 500 times less but I'am not sure how the script works right now).

**Comment by hugolpz** [comment]
(some message errors corrected)

**Comment by kanasimi** [comment]
I rewrite some codes and maybe it meets you request now?

**Comment by hugolpz** [comment]
### .download() bentchmark (3)
I tested today with n=805.
- Initial downloads : 
  - categorymembers=805
  - downloads=805
  - runing time: 9'53" (593secs)
  - average : 0.74 sec/download.
- Removed 20 files from local directory 
- Update downloads: 
  - categorymembers=805
  - downloads=20
  - runing time: 5'20" (320secs)
  - average : 0.40 sec/file
  - average : 16 sec/download

**Performance increase**
- **Initial downloads: 3.8 times (2.7s->0.74s) improvement**
- **Update downloads: 2.4 times (38.6s -> 16s) improvement**

compated to [`.download() bentchmark` 7 days prior](https://github.com/kanasimi/wikiapi/issues/51#issue-1089311016).** 🎇

**Comment by kanasimi** [comment]
Well, in fact I am using generator now. you may find the codes at https://github.com/kanasimi/CeJS/blob/master/application/net/wiki/page.js#L3891

**Comment by hugolpz** [comment]
@kanasimi , issue 52 took us a lot of energy. I assume you also have a busy professional life. 
So let's pause this issue 51 for some days and return to it later on ok for you ? (this weekend ?)

**Comment by kanasimi** [comment]
OK.

**Comment by hugolpz** [comment]
This scale up question is handled in several related issues:
- [x] #55 
- [ ] #53
