### ISSUE TITLE
`.download()` : reduce calls to api.php, directly hit on https://upload.wikimedia.org

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#53]
```javascript 
/* ************************************************************* */
/* *********                                      ************** */
/* *********       REWRITING ONGOING.             ************** */
/* *********         DO NOT READ YET.             ************** */
/* *********                                      ************** */
/* ************************************************************* */
```

I don't know how cejs and WikiapiJS' `.download()` currently handles its queries, but I suspect it list the target files in an array via `.categorymembers()`, `.search()` or others which returns something such:

**Categorymembers files:**
```javascript
// var files = await targetwiki.categorymembers('Category:Lingua Libre pronunciation-cmn', { namespace: 'File' });
// returns : 
[
  {"pageid":98560779,"ns":6,"title":"File:LL-Q9192 (cmn)-Assassas77-不.wav"},
  {"pageid":98560774,"ns":6,"title":"File:LL-Q9192 (cmn)-Assassas77-了.wav"},
  ....
  {"pageid":98560798,"ns":6,"title":"File:LL-Q9192 (cmn)-Assassas77-什么.wav"},
]
```

then **use pageid to run a new API query for each file, get the url, and download the file**.

### Limits

| Source | Comment |
| ---- | ---- |
| https://commons.wikimedia.org/w/api.php? | API queries have `ratelimit` 
| https://upload.wikimedia.org | Direct downloads don't (I'm not 100% sure for that 😅 ).

### Wikimedia API and group queries
There are [Special:ApiSandbox queries](https://commons.wikimedia.org/wiki/Special:ApiSandbox#action=query&format=json&prop=imageinfo&generator=categorymembers&iiprop=url%7Ctimestamp&iimetadataversion=1&iiextmetadatafilter=Categories&gcmtitle=Category%3ALingua_Libre_pronunciation-fra&gcmprop=ids%7Ctitle&gcmnamespace=6&gcmlimit=500) which using a single API call can fetch by category name few hundred category member files, with exact file url and timestamp.

```javascript
{
  "batchcomplete": "",
  "continue": {
    "gcmcontinue": "file|313235300a4c4c2d513135302028465241292d504f534c4f56495443482d313235302e574156|88497069",
    "continue": "gcmcontinue||"
  },
  "query": {
    "pages": {
      "82101585": { ... },
      "104331639": {
        "pageid": 104331639,
        "ns": 6,
        "title": "File:LL-Q150 (fra)-Kitel WP-%.wav",
        "imagerepository": "local",
        "imageinfo": [{
          "timestamp": "2021-04-25T15:49:00Z",
          "url": "https://upload.wikimedia.org/wikipedia/commons/a/a3/LL-Q150_%28fra%29-Kitel_WP-%25.wav",
          "descriptionurl": "https://commons.wikimedia.org/wiki/File:LL-Q150_(fra)-Kitel_WP-%25.wav",
          "descriptionshorturl": "https://commons.wikimedia.org/w/index.php?curid=104331639"
        }]
      },
      "104381091": { ... }
    }
  }
}
```
`title`, `timestamp` and `url` are the most relevant properties I believe.

See also: [API:Categorymembers](https://www.mediawiki.org/wiki/API:Categorymembers), <s>[API:Allimages](https://mediawiki.org/wiki/API:Allimages)</s>, [API:Imageinfo](https://mediawiki.org/wiki/API:imageinfo).

### Url
For files, the url property gives a direct download url allowing download from `upload.wikimedia.org` without additional API query on `https://commons.wikimedia.org/w/api.php?`.
With one API query we can have 500 direct url to download from at higher speed.

### Sustained "burst" management
The Wikimedia Discord api-bot channel made several input to this projects:
- [meta:User-Agent_policy](https://meta.wikimedia.org/wiki/User-Agent_policy)
- [Discord discussion](https://discord.com/channels/178359708581625856/417008204669779969/925502428873359472)
  - concensus: limit to 5~8 concurrent downloads.
  - @Anticomposite: make requests from only one IP
  - @Ciencia-Al-Poder: file requests are not stored on normal filesystem. Due to the large set of files uploaded to commons, they're stored on swift (IIRC), and it may incure in some overhead specially when requesting files that nobody requested in a long time
  - @Marreromarco using Wikiget reported an average of 10 download per seconde (730,000 files in 20hours).
    - Done by running Wikiget in 20 terminals in parallel.
  - An average of 100 downloads per second is not unheard of but likeky requires careful request header and whitelisting.
  - Resilience when internet connexion is unstable may help.

**Comment by hugolpz** [comment]
Hello Kanasimi,

### Current speed
The `.download() bentchmark` section above shows `.download()` to have a conservatively slow performance.
Per code analysis, I understand `.download()` takes as input objects such as:

```javascript
{ 
  "pageid":104331639,
  "ns":6,
  "title":"File:LL-Q150 (fra)-Kitel WP-%.wav"
}
```

**Such input means `.download()` initially miss the `url` and `timestamp`, therefore must run one additional API call per file, which is rate limited** to get the `url` and `timestamp`. This results in the observed speed limitation of about 1 file per 2.7 seconds. This ratelimited API call also occurs when the file is eventually skipped because already present locally.

### Speed optimization idea
However, `await targetwiki.categorymembers('Category:Lingua Libre pronunciation-cmn', { namespace: 'File' });`, when operating with `namespace: 'File'` (`ns:6`), could leverage [smarter API queries](https://commons.wikimedia.org/wiki/Special:ApiSandbox#action=query&format=json&prop=imageinfo&generator=categorymembers&iiprop=url%7Ctimestamp&iimetadataversion=1&iiextmetadatafilter=Categories&gcmtitle=Category%3ALingua_Libre_pronunciation-fra&gcmprop=ids%7Ctitle&gcmnamespace=6&gcmlimit=500) requiring `imageinfo` (see section "Wikimedia API and group queries" above). Each smart API call run within `.categorymember()` can return 500 richer objects such as : 

```javascript
  { 
    "pageid":104331639,
    "ns":6,
    "title":"File:LL-Q150 (fra)-Kitel WP-%.wav",
    "timestamp": "2021-04-25T15:49:00Z",
    "url": "https://upload.wikimedia.org/wikipedia/commons/a/a3/LL-Q150_%28fra%29-Kitel_WP-%25.wav"
  },
```

If input with such format is passed down, `.download()` can :
- skip the ratelimited API call on `https://commons.wikimedia.org/w/api.php`
- `url` value used to directly download from `https://upload.wikimedia.org`. According to discussion on Wikimedia's Discord, this api point accept 20~100 times more requests than the other one (if header request properly set).
-`timestamp` value used to directly compare with local files creation times. Files can be compared in milliseconds instead of 0.29 seconds. (factor x10-100)

### Code to do (proposal)

1. If `.categorymembers()` looks for `Files`, then use smart api generator, return array of object with pageid, ns, title AND `url`, `timestamp`.
2. If `.download()`'s input options contains `url` && `timestamp`, then :
  - skip call on `https://commons.wikimedia.org/w/api.php` / do not call API
  - compare: if local file with same name exists, directly compare timestamp value with local file timestamp, 
  - download: if no local file with same name OR update needed, directly download file via query on `https://upload.wikimedia.org`.

**Comment by hugolpz** [comment]
I'm not sure of which of the proposals you implemented. 

### .download() bentchmark (2)
I tested today with n=805.
- Initial downloads : 
  - categorymembers=805
  - downloads=805
  - runing time: 12'10" (730secs)
  - average : 0.9 sec/download.
- Removed 20 files from local directory 
- Update downloads: 
  - categorymembers=805
  - downloads=20
  - runing time: 5'10" (310secs)
  - average : 0.38 sec/file
  - average : 15.5 sec/download

**Performance increase**
- **Initial downloads: 3 times (2.7s->0.9s) improvement**
- **Update downloads: 2.5 times (38.6s -> 15.5s) improvement**

compated to [`.download() bentchmark` 7 days prior](https://github.com/kanasimi/wikiapi/issues/51#issue-1089311016).** 🎇 

**File comparison**
In the "Update downloads" phase...
Accounting for the observed `60s` for listing of target files and `20*0.9s` for actual downloads = 80s.
Comparing local file and remote file's timestamps takes : 
- 310s - 80 = 230secs allocated to such comparison
- 230 / (805-20)= **0.29s / file comparison**.

(This seems consistent with an API call on `https://commons.wikimedia.org/w/api.php` for `timestamp` + comparison with local file's `timestamp`.)

### Questions
Q1: @kanasimi, the performances of this last benchmark and some calculation suggest that either the code is speed limited or each `.download()` run still make
- one API call on `https://commons.wikimedia.org/w/api.php` to fetch `url` and `timestamp` parameters
- one call on  `https://upload.wikimedia.org` for the file itself.

Is that correct ?

Q2: How do you limit the speed ? You simply make those calls in synchronous js, right ?

### Comment
I suspect some [optimization ideas here](https://github.com/kanasimi/wikiapi/issues/51#issuecomment-1003020742) could still be implemented if wanted.

**Comment by hugolpz** [comment]
Hello Kanasimi, 
Benchmark 3 done ! : )
I'm a bit blind on your recent changes but they appear to have speeded up the initial downloads.

We need slower coding and more discussion please. 🐨 🦦  I think the changes you implemented are different from those proposed [here](https://github.com/kanasimi/wikiapi/issues/51#issuecomment-1003020742). Since you are good in JS you are used to go straight into coding, you move faster this way and it's usually the best choice, you indeed came up with nice improvements. But by doing so I'm sidelined, I don't know what you are coding, I can't confirm we think about the same idea. We both push for performance improvements, but it seem we pushed for _different_ solutions.
Can we discuss the proposed change above so we confirm we talk about the same thing, and we properly look at it, accept or deny it ? A brief explanation why this proposal is not practical for cejs, which is also possible, would be ok. See also the [questions here](https://github.com/kanasimi/wikiapi/issues/51#issuecomment-1004376364) where I try to understand the current code's approach.

### .download() bentchmark (3)
I tested today with n=805.
- Initial downloads : 
  - categorymembers=805
  - downloads=805
  - runing time: 9'53" (593secs)
  - average : 0.74 sec/download.
- Removed 20 files from local directory 
- Update downloads: 
  - categorymembers=805
  - downloads=20
  - runing time: 5'20" (320secs)
  - average : 0.40 sec/file
  - average : 16 sec/download

**Performance increase**
- **Initial downloads: 3.8 times (2.7s->0.74s) improvement**
- **Update downloads: 2.4 times (38.6s -> 16s) improvement**

compated to [`.download() bentchmark` 7 days prior](https://github.com/kanasimi/wikiapi/issues/51#issue-1089311016).** 🎇 

### Inpecting `categorymembers()`
I see 
```javascript
var files = await targetwiki.categorymembers(targetCategoryName, { namespace: 'File' });
console.log(files[0], files[1], files[2])
```
...still currently returns (cejs from today):
```javascript
{
  pageid: 113936425,
  ns: 6,
  title: 'File:LL-Q9192 (cmn)-Luilui6666-102 块钱.wav'
} {
  pageid: 113936375,
  ns: 6,
  title: 'File:LL-Q9192 (cmn)-Luilui6666-102块钱.wav'
} {
  pageid: 113936358,
  ns: 6,
  title: 'File:LL-Q9192 (cmn)-Luilui6666-17-45.wav'
}
```

this is then passed to `.download()`. It miss the `url` and `timestamp` parameters which would allow faster execution with 500 times fewer API calls on ratelimited `https://commons.wikimedia.org/w/api.php`. See [proposal here](https://github.com/kanasimi/wikiapi/issues/51#issuecomment-1003020742).

**Comment by kanasimi** [comment]
Hi.

When executing `session.download('Category:name', ...)`,
wiki_API_download() will:
1. Get category tree without files, using session.category_tree(). session.category_tree() will use categoryinfo and categorymembers (category only) to increase speed.
2. Back to wiki_API_download(). For each category, get imageinfo (with URL, latest date) with generator:categorymembers to get files in category.
3. For each file, check timestamp and download new file.

**Comment by kanasimi** [comment]
You can try this now: `await wiki.download('Category:Lingua Libre pronunciation', { directory: './downloads', max_threads: 4 });`

**Comment by hugolpz** [comment]
> 3. For each file, check timestamp and download new file.

IMPORTANT/CORE OF THIS ISSUE : Do you :
* A) a) use the `pageid` + a call to `commons.wikimedia.org/w/api.php` to fetch the true `url` value, b) then hit on `upload.wikimedia.org`download on
OR!
* B) a) use generator:categorymembers's provided `url` do you directly hit on `upload.wikimedia.org`
??

**Comment by kanasimi** [comment]
All imageinfo are get with generator:categorymembers.

**Comment by hugolpz** [comment]
I'am double checking my packages and running a benchmark.

**Comment by kanasimi** [comment]
Ok
