### ISSUE TITLE
`.download()` : compare local and remote files by timestamps before downloading

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#55]
```
SPLIT OF PREVIOUS ISSUES. 
NEW CONCLUSION IS INTERESTING.
CAN BE CLOSED !
```

### Timestamp
Timestamp property could be used to compare with existing local file's timestamp.
If API timestamp property is smaller (older) than local file timestamp, then skip download.
The imageinfo's `"timestamp": "2021-04-25T15:49:00Z"` indeed matches [file description page](https://commons.wikimedia.org/wiki/File:LL-Q150_(fra)-Kitel_WP-%25.wav) indicating : 

|  | Date/Time | Thumbnail | Dimensions | User | Comment
| -- | -- | -- | -- | -- | --
| current | 15:49, 25 April 2021 |   | 1.1 s (99 KB) | Kitel WP (talk \| contribs) |  

After verification, files with several uploads provide by default the timestamp of the last upload (default : 1 revision, the latest).

### Q4-related (✅ #51)
When a file already exists locally, it could be skipped faster.
Given `a` the _time per download_, `x` the _number of files to download_, `b` the _initial categorymember query time_ with estimated `b=60sec`. We could get the second attempt (update) duration to be such as `2.7*14+60 = 97.8secs` instead of 540 sec.

### Q5-related (✅ #51)
@Poslovitch pointed out that filenames are not enough, some versioning check may be ongoing so recently updated files on commons are indeed re-downloaded. ([Discord server invitation](https://discord.gg/c7M2ufzQ))
Ciencia-Al-Poder pointed out _"First of all, you should avoid redownload files that you downloaded on a previous run. The api will return you the file modification/creation time. Use it to check if the file has been updated."_ ([Discord link](https://discord.com/channels/178359708581625856/417008204669779969/925083188890595349))

**Comment by hugolpz** [comment]
@kanasimi posted:
> Hi. Maybe you will be interesting in `const file_data_list = await wiki.download('Category:name', { directory: './' });`
> The conceptions are implemented now, I am using generator now. The codes will do as less calls as possible. You may try it yourself.
> You may try it yourself and find the codes at https://github.com/kanasimi/CeJS/blob/master/application/net/wiki/page.js#L3893

**Comment by hugolpz** [comment]
### Mini benchmark
- Initial download: 
  - 760s/829 ⬇️ = 0.9s/ ⬇️
- Update downloads:
  - ~20s/829 🔉 / 20 ⬇️ = ~0.02s/file comparison and ~1s/⬇️

UPDATE IS DAMN FASTER INDEED !!! 🎆

**Comment by kanasimi** [comment]
Well, I think this issue is solved.

**Comment by hugolpz** [comment]
200 times faster 😻🙉🤤
