### ISSUE TITLE
Provide an option to set a custom User-Agent string

### ISSUE THREAD

**Issue by strefethen** [kanasimi/wikiapi#65]
I can't seem to find a decent place to change the default User-Agent used in the library. Wikipedia has a [User-Agent policy](https://meta.wikimedia.org/wiki/User-Agent_policy) which calls for a specific User-Agent string and it would be great if there were an option to provide a custom User-Agent which was specific to the calling application vs. the wikiapi package.

Regards,
Steve

**Comment by kanasimi** [comment]
By default, the library will use the user agent `get_URL_node.default_user_agent` set in [Ajax.js](https://github.com/kanasimi/CeJS/blob/master/application/net/Ajax.js). If you want to [set another user agent](https://meta.wikimedia.org/wiki/User-Agent_policy), you can change `CeL.wiki.query.get_URL_options.get_URL_options` listed in [query.js](https://github.com/kanasimi/CeJS/blob/master/application/net/wiki/query.js):
```javascript
CeL.wiki.query.get_URL_options.headers['User-Agent'] = 'testbot/1.0';
```

**Comment by strefethen** [comment]
Thank you!!

**Comment by strefethen** [comment]
@kanasimi any timeline for an updated release to NPM?

**Comment by kanasimi** [comment]
I'm still testing new features, so please wait some days.
