### ISSUE TITLE
New Logo for framework !

### ISSUE THREAD

**Issue by hugolpz** [kanasimi/wikiapi#66]
https://commons.wikimedia.org/wiki/File:WikiapiJS_MW_gear_icon.svg

**Comment by kanasimi** [comment]
Thank you so much!

**Comment by hugolpz** [comment]
I made a presentation about Wikidata, one slide was about Bot.
PyWikiBot has an elegant SVG logo but we don't. I took the opportunity to derivate it into a correct logo 😸
