### ISSUE TITLE
Feature Request: Verbose mode

### ISSUE THREAD

**Issue by Cobertos** [kanasimi/wikiapi#9]
I noticed a lot of commented `console.log`s and `console.trace`s in the code.

It would be nice if those could be toggled on/off with a flag. It would help when running in CI so that bugs from production edits can be caught easier.

Nice library btw, very versatile :D

**Comment by kanasimi** [comment]
Thank you for trying this library.
You may set `CeL.set_debug()` or `CeL.set_debug(3)` (1-9) to get more debug information.

**Comment by Cobertos** [comment]
Ah I see, it's a part of CeL, that helps. Thanks!
